### ISSUE TITLE
Avoid having password in plaintext

### ISSUE THREAD

**Issue by atehrani** [kgv7/hb-project#1]
Consider avoid storing the password in plaintext in the database. The general approach is to one-way hash the password (using some salt) and storing that into the database. Then comparing that one-way hash with the plaintext input (hashed) from the user.
https://github.com/kgv7/hb-project/blob/281d1929827165701e919b6d7fe1647f544d15fd/api/crud.py#L9

You can do this hashing in Python or even in the DB itself. I'll leave that to the author to determine the best route to do so.

This article explains it in far greater detail: https://auth0.com/blog/hashing-passwords-one-way-road-to-security/

**Comment by kgv7** [comment]
Thanks @atehrani! That's a great suggestion and I will work on implementing!

**Comment by kgv7** [comment]
@atehrani - Fixed using werkzeug's `generate_password_hash()`:
https://github.com/kgv7/hb-project/blob/main/api/crud.py#L10

And then used werkzeug's `check_password_hash()` to verify password when user logs in:
https://github.com/kgv7/hb-project/blob/main/api/server.py#L202

**Comment by atehrani** [comment]
@kgv7 Excellent! Thanks for looking into it and addressing it
